In [2]:
import numpy as np;

import os
path = os.path.abspath(os.getcwd())
k_l = path + "/notebooks/calib-results/cam_mats_left.npy"
k_r = path + "/notebooks/calib-results/cam_mats_right.npy"
np.load(k_l)


array([[504.38498235,   0.        , 321.92247118],
       [  0.        , 504.38498235, 188.63481707],
       [  0.        ,   0.        ,   1.        ]])

In [3]:
np.load(k_r)

array([[504.38498235,   0.        , 312.85543989],
       [  0.        , 504.38498235, 185.66272695],
       [  0.        ,   0.        ,   1.        ]])

P = K * [R | t] 

In [8]:
rot_f = path + "/notebooks/calib-results/rot_mat.npy"
r = np.load(rot_f)
r

array([[ 0.99945835, -0.00714085,  0.03212484],
       [ 0.00760995,  0.99986585, -0.01450387],
       [-0.03201696,  0.01474048,  0.99937862]])

In [9]:
trans_f = path + "/notebooks/calib-results/trans_vec.npy"
t = np.load(trans_f)
t

array([[ 8.36676026e+00],
       [ 2.99845668e-03],
       [-1.24471830e+00]])

In [11]:
T = np.hstack((r, t))
T

array([[ 9.99458355e-01, -7.14084857e-03,  3.21248352e-02,
         8.36676026e+00],
       [ 7.60994684e-03,  9.99865854e-01, -1.45038657e-02,
         2.99845668e-03],
       [-3.20169559e-02,  1.47404780e-02,  9.99378623e-01,
        -1.24471830e+00]])

In [13]:
proj_f = path + "/notebooks/calib-results/proj_mats_left.npy"
Pl = np.load(proj_f)
Pl

array([[504.38498235,   0.        , 377.38433337,   0.        ],
       [  0.        , 504.38498235, 182.30455971,   0.        ],
       [  0.        ,   0.        ,   1.        ,   0.        ]])

In [14]:
proj_f = path + "/notebooks/calib-results/proj_mats_right.npy"
Pl = np.load(proj_f)
Pl

array([[5.04384982e+02, 0.00000000e+00, 4.18621510e+02, 4.26651293e+03],
       [0.00000000e+00, 5.04384982e+02, 1.82304560e+02, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])